default_stages: [commit, push]
default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: check-case-conflict
- repo: local
  hooks:
  - id: pylint
    name: Pylint
    entry: pylint
    args:
    - --ignore-imports=yes
    - -E
    exclude: examples
    language: python
    types: [python]
  - id: flake8
    name: Flake8
    entry: flake8
    language: python
    types: [python]
    require_serial: true
