default_stages: [commit, push]
default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
  - id: forbid-tabs
  - id: insert-license
    name: Add license for all python files
    types: [python]
    args:
    - --comment-style
    - "|#|"
    - --license-filepath
    - src/LICENSE.txt
    - --fuzzy-match-generates-todo
  - id: insert-license
    name: Add license for all rst files
    args:
      - --comment-style
      - "||"
      - --license-filepath
      - docs/LICENSE.rst
      - --fuzzy-match-generates-todo
    files: \.rst$
- repo: local
  hooks:
  - id: pylint
    name: Pylint
    entry: pylint
    args:
    - --ignore-imports=yes
    - -E
    exclude: examples
    language: python
    types: [python]
  - id: flake8
    name: Flake8
    entry: flake8
    language: python
    types: [python]
    require_serial: true
