repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
- repo: local
  hooks:
  - id: pylint
    args:
    - --ignore-imports=yes
    - -E
    name: pylint
    exclude: examples
    entry: pylint
    language: system
    types: [python]
