logcfg = "logging.ini"

[RUNNER]
default = "dask"

[RUNNER.dask]
provider = "dask"
scheduler = "multiprocessing"

[RUNNER.graphviz]
provider = "graphviz"
format = "png"


[REGISTRY]
default = "homedir"

[REGISTRY.virtual]
provider = "virtual"

[REGISTRY.homedir]
provider = "filesystem"
#path = ~/.forml/registry


[FEED]
default = ["presto"]

[FEED.presto]
provider = "presto"
priority = 100
host = "localhost"
port = 8080


[SINK]
default = "stdout"
train = "stdout"
apply = "stdout"
eval = "stdout"

[SINK.stdout]
provider = "stdout"
