logcfg = "logging.ini"

[PLATFORM]
feed = "presto"
runner = "dask"
registry = "homedir"

[FEED.presto]
provider = "presto"
priority = 100
host = "localhost"
port = 8080

[RUNNER.dask]
provider = "dask"
scheduler = "multiprocessing"

[RUNNER.graphviz]
provider = "graphviz"
format = "png"

[REGISTRY.virtual]
provider = "virtual"

[REGISTRY.homedir]
provider = "filesystem"
#path = ~/.forml/registry

[TESTING]
runner = "dask"
